resource_paths:
  pseudo1: path1
  pseudo2: path2

page_size_default:
  homepage_videos: 5
  homepage_tags: 20
  searchpage: 15

suggestion_limit:
  name: 10
  author: 10
  tag: 20

video_extensions:
  - .mp4
  - .avi
  - .mkv
  - .mov
  - .wmv
  - .flv
  - .webm
  - .m4v
  - .mpg
  - .mpeg

# MongoDB config
mongo:
  host: localhost
  port: 27017
  database: video_tag_db
  username: exampleUser001
  password: examplePassword